[package]
name = "proto"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Shared protocol types for websocket frames, auth DTOs, and session state"

[dependencies]
serde.workspace = true
serde_json.workspace = true