[package]
name = "utils"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Common utilities and helper functions for the rehearsal platform"

[dependencies]
# No external dependencies needed for basic utilities